# buildspec.yml
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8  # Specify the Python version
    commands:
      - echo "Installing dependencies if needed"
      
  build:
    commands:
      - echo "Preparing sys_info.py for deployment"
  
artifacts:
  files:
    - sys_info.py
  discard-paths: yes
  base-directory: .
  # Replace <your-s3-bucket-name> with your S3 bucket name.
  # This will push the sys_info.py to a specified S3 bucket.
artifacts:
  files:
    - sys_info.py
  name: sys_info_build.zip
  discard-paths: yes
  base-directory: .
