version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Build started on `date`
      - python sysinfo.py  # You may want to ensure the script performs actions directly
  post_build:
    commands:
      - echo Build completed on `date'

artifacts:
  files:
    - '**/*'  # Adjust this as needed, depending on what you want to include in the artifact
