version: 0.2

phases:
  install:
    commands:
      echo "Installing dependencies"
      # You can install any dependencies for building here
  build:
    commands:
      echo "Creating artifact directory"
      mkdir -p artifact
      cp sys_info.py artifact/
  post_build:
    commands:
      echo "Uploading artifact to S3"
      aws s3 cp artifact/ s3://cicd-sysinfo/sysinfo-clone/BuildArtif/ --recursive

artifacts:
  files:
    - artifact/**


