version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x  # Specify the Python version
    commands:
      - echo Installing dependencies...
     # - pip install -r requirements.txt  # Install dependencies if needed
  build:
    commands:
      - echo Build started on `date`
      - echo Bundling the tool...
      - mkdir -p artifact  # Create a directory to store the artifact
      - cp sysinfo.py artifact/  # Copy the Python script to the artifact directory
      - cd artifact
      - zip -r sysinfo.zip .  # Zip the contents into an artifact
      - cd ..  # Go back to the previous directory
      - echo Build completed on `date`

# No artifacts section needed if configured in the CodeBuild settings
