version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x  # Specify the Python version you need
    commands:
      - echo Installing dependencies...
  build:
    commands:
      - echo Build started on `date`
      - echo Bundling the tool...
      - ls -al
      - mkdir -p artifact  # Create a directory for the artifact
      - cp sys_info.py artifact/  # Copy the Python script into the artifact directory
      - cd artifact
      - zip -r sysinfo.zip .  # Zip the contents into an artifact
      - cd ..  # Go back to the previous directory
      - echo Build completed on `date`
