version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo Installing dependencies...
     # - pip install -r requirements.txt  # Only if you have any dependencies like psutil
  build:
    commands:
      - echo Packaging the tool..
      - ls 
      - mkdir -p build/artifact
      - cp -r build/artifact/
  post_build:
    commands:
      - echo Uploading artifact to S3...
      - aws s3 cp build/artifact/ s3://cicd-sysinfo/sysinfo-clone/ --recursive


