version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo Installing dependencies...
     # - pip install -r requirements.txt  # Only if you have any dependencies like psutil
  build:
    commands:
      - ls 

artifacts:
  files:
    - '**/*'
  base-directory: .


