version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x  # Specify the Python version
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt  # Install dependencies if you have any
  build:
    commands:
      - echo Build started on `date`
      - echo Bundling the tool...
      - mkdir -p artifact  # Create a directory to store the artifact
      - cp sysinfo.py artifact/  # Copy the Python script to the artifact directory
      - cd artifact
      - zip -r sysinfo.zip .  # Zip the contents into an artifact
      - cd ..  # Go back to the previous directory
      - echo Build completed on `date`

artifacts:
  files:
    - artifact/sysinfo.zip  # Specify the artifact to upload
  discard-paths: yes  # Optional: Discard the directory structure and only keep the file

# Optional: Environment Variables (if needed)
# env:
#   variables:
#     S3_BUCKET: "your-bucket-name"
#     S3_KEY: "path/to/sysinfo.zip"

# Optional: Post-build commands to upload the artifact to S3
post_build:
  commands:
    - echo Uploading the artifact to S3...
    - aws s3 cp artifact/sysinfo.zip s3://your-bucket-name/path/to/sysinfo.zip
