version: 0.2
env:
  variables:
    ANSIBLE_SSH_EXTRA_ARGS: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      # Install necessary dependencies
      - pip install -r requirements.txt


  build:
        commands:
          - ls -al
          - pd=$(pwd)
          - echo "Creating dyanmic inventory file"
          - python3 ansible/dynamic_inventory.py > dynamic_inventory.json
          - cat dynamic_inventory.json
          - echo "Running Ansible Playbook to deploy to Linux and Windows"
          - ansible-playbook ansible/playbooks/deploy_code.yml -i dynamic_inventory.json -e "path=$pd"

artifacts:
  files:
    - ansible/playbooks/files/**
  discard-paths: no
