version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies if needed"
      
  build:
    commands:
      - echo "Preparing sys_info.py for deployment"
  
artifacts:
  files:
    - sys_info.py
  base-directory: BuildArtif/SourceArti
  discard-paths: yes
  name: sys_info_build.zip  # Sets a consistent artifact name
