version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      # Install required libraries
      - pip install boto3 ansible
      - echo "Install complete"

  pre_build:
    commands:
      - echo "Retrieving Secrets from AWS Secrets Manager"
      - SECRET_LINUX_SSH_KEY=$(aws secretsmanager get-secret-value --secret-id linux-ssh-key --query SecretString --output text)
      - SECRET_WINDOWS_PASSWORD=$(aws secretsmanager get-secret-value --secret-id windows-admin-password --query SecretString --output text)
      - echo "Secrets retrieved successfully"

  build:
    commands:
      # Set environment variables for Ansible to use
      - echo "Running Ansible Playbook to deploy to Linux and Windows"
      - ansible-galaxy collection install amazon.aws
      - ansible-inventory -i ansible/inventory/demo.aws_ec2.yml --list 
      - ansible tag_Name_linux_sysinfo -m ping -v
#      - ansible-playbook -i ansible/inventory/demo.aws_ec2.yml ansible/playbooks/deploy_code.yml

artifacts:
  files:
    - '**/*'
  base-directory: .


