version: 0.2
env:
  variables:
    ANSIBLE_SSH_EXTRA_ARGS: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      # Install necessary dependencies for Ansible and AWS CLI
      - pip install ansible  boto3

  pre_build:
    commands:
      # Retrieve Linux PEM key from Secrets Manager
      - echo "Retrieving PEM key for Linux from Secrets Manager"
      - aws secretsmanager get-secret-value --secret-id linux-ssh-key --query SecretString --output text > private_key.pem 
      - chmod 600 private_key.pem  # Set appropriate permissions for the PEM file

      # Retrieve Windows credentials from Secrets Manager
   #   - echo "Retrieving Windows credentials from Secrets Manager"
   #   - RAWOUTPUT=$(aws secretsmanager get-secret-value --secret-id windows-admin-password --query SecretString --output text)
    #  - export WIN_USERNAME="Administrator"
     # - export WIN_PASSWORD=$(echo $RAWOUTPUT | jq -r '.["windows-admin-password"]')

  build:
        commands:
          # Set environment variables for Ansible to use
          - echo "Running Ansible Playbook to deploy to Linux and Windows"
          - ansible-galaxy collection install amazon.aws
          - ansible-inventory -i ansible/inventory/demo.aws_ec2.yml --list
          - ls -al
          - cat private_key.pem
          - python3 ansible/dynamic_inventory.py > dynamic_inventory.json
          - ls -al
          - cat dynamic_inventory.json
#          - ansible all -m debug -a "var=group_names" -i dynamic_inventory.json
          - ansible all -m ping -i dynamic_inventory.json

artifacts:
  files:
    - '**/*'
  base-directory: .
