plugin: amazon.aws.aws_ec2
regions:
  - ap-south-1  # Specify your AWS region
filters:
  # Filter instances by tags
  tag:Name:
    - "linux-sysinfo"
    - "windows-sysinfo"
keyed_groups:
  - key: tags.Name  # Group by 'Name' tag (e.g., linux-sysinfo, tag_Name_windows_sysinfo)
    prefix: "tag_Name"
hostnames:
  - dns-name  # Use the public DNS name if available, otherwise fall back to private IP
  - private-ip  # Use private IP as fallback if DNS name is not available

