---
- name: Deploy to EC2 instances
  hosts: all 
  gather_facts: yes
  vars:
    build_artifact_directory: "{{ path }}/ansible/playbooks/files/sys_info.py"  
    linux_deployment_directory: "/home/ec2-user"  
    windows_deployment_directory: "C:\\temp"  
  tasks:
    
    - name: Deploy on Linux
      when: ansible_facts['os_family'] == 'RedHat'  
      ansible.builtin.copy:
        src: "{{ build_artifact_directory }}"
        dest: "{{ linux_deployment_directory }}/"
        mode: '0644'
        owner: 'ec2-user' 

    - name: Deploy on Windows
      when: ansible_facts['os_family'] == 'Windows'  
      ansible.windows.win_copy:
        src: "{{ build_artifact_directory }}"
        dest: "{{ windows_deployment_directory }}\\"

