---
- name: Deploy to EC2 instances
  hosts: all # Target Linux instances with the 'linux-sysinfo' tag
  gather_facts: yes
  vars:
    build_artifact_directory: "/sys_info.py"  # Local build directory
    linux_deployment_directory: "/home/ec2-user"  # Deployment directory on Linux
    windows_deployment_directory: "c:\temp"  # Deployment directory on Windows
  tasks:
    
    - name: Ensure the system is up-to-date on Linux
      when: ansible_facts['os_family'] == 'RedHat'  # For Linux (or adjust based on your system)
      ansible.builtin.copy:
        src: "{{ build_artifact_directory }}"
        dest: "{{ linux_deployment_directory }}/"

    - name: Ensure the system is up-to-date on Windows
      when: ansible_facts['os_family'] == 'Windows'  # For Windows
      ansible.windows.win_copy:
        src: "{{ build_artifact_directory }}"
        dest: "{{ windows_deployment_directory }}\"

