---
- name: Generate dynamic inventory from EC2 instances based on tags
  hosts: all
  gather_facts: yes
  tasks:
    - name: Print system information
      debug:
        msg: "This host is {{ ansible_facts['os_family'] }} with IP {{ ansible_host }}."
      when: ansible_facts['os_family'] is defined
    - name: Generate custom inventory output
      template:
        src: dynamic_inventory.j2
        dest: ./dynamic_inventory.ini
      delegate_to: localhost
      run_once: true

